default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: user123
  host: 192.168.1.100
  port: 3306
  timeout: 5000

development:
  <<: *default
  database: seguros_gt


